#!/usr/bin/env python
from __future__ import annotations

from pathlib import Path
import argparse
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from ravel_lm.config import RavelConfig
from ravel_lm.model import RavelLM


def main() -> None:
    p = argparse.ArgumentParser(description="Count parameters for RAVEL configs")
    p.add_argument("configs", nargs="*", default=None)
    p.add_argument("--markdown", default=None)
    args = p.parse_args()
    paths = [Path(x) for x in args.configs] if args.configs else sorted((ROOT / "configs").rglob("*.json"))
    rows = []
    for path in paths:
        path = path.resolve()
        cfg = RavelConfig.from_json(path)
        model = RavelLM(cfg)
        rows.append((str(path.relative_to(ROOT)), cfg.name, cfg.vocab_size, cfg.d_model, cfg.n_layers, model.num_parameters))
    header = ("config", "name", "vocab", "d_model", "layers", "params")
    print(f"{header[0]:36s} {header[1]:18s} {header[2]:>7s} {header[3]:>7s} {header[4]:>6s} {header[5]:>12s}")
    for r in rows:
        print(f"{r[0]:36s} {r[1]:18s} {r[2]:7d} {r[3]:7d} {r[4]:6d} {r[5]:12,d}")
    if args.markdown:
        lines = ["# Parameter count evidence", "", "Generated by `python scripts/count_params.py --markdown docs/PARAM_COUNTS.md`.", "", "| config | name | vocab | d_model | layers | params |", "|---|---:|---:|---:|---:|---:|"]
        for r in rows:
            lines.append(f"| `{r[0]}` | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]:,} |")
        Path(args.markdown).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
